name: Formal Verification Workflow

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  formal-verif:
    name: Formal Verification
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Verify with Kani
        uses: model-checking/kani-github-action@0.23
